### ISSUE TITLE
async network request

### ISSUE THREAD

**Issue by rodwanb** [SuavePirate/Xamarin.Flux#3]
Hi, 

I am interested to know how and where the long running web request will fit into this architecture.
If possible could you include one in your sample app.

Regards
Rodwan

**Comment by SuavePirate** [comment]
I personally would create a separate `Service` type class  to actually make the request then have an `Action` that invokes it. Once the service returns the result of the long running request (or intermittent events if you want a progress bar sort of thing), the action would dispatch the event to the stores that want to listen to it so they can update their data.

I don't have time to update the example project right now since I have a whole lot more going on, but there are tons of examples of doing this with flux in javascript that you could follow along with and adjust for C#

**Comment by rodwanb** [comment]
Thank you for the feedback. I see that in the javascript world they use the callbacks to fire off the next action with the result object. In the c# world would this mean that actions are now awaitable tasks instead of void methods?
